import type { Metadata } from "next";
import { Syne } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { cn } from "@/lib/utils";
import Header from "@/components/Header";

const inter = Syne({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body className={cn(inter.className, "")}>
				<ThemeProvider
					attribute='class'
					defaultTheme='dark'
					enableSystem
					disableTransitionOnChange>
					<div className='w-full max-w-full mx-auto relative'>
						<div className='absolute w-full top-1 p-4 z-50'>
							<Header />
						</div>
						<div className='h-[40px]'>{children}</div>
					</div>
				</ThemeProvider>
			</body>
		</html>
	);
}
